services:
  jenkins-controller:
    image: jenkins/jenkins:lts
    container_name: jenkins-controller
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-network

  ssh-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssh-agent
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    volumes:
      - jenkins_agent_volume:/home/jenkins/agent
    depends_on:
      - jenkins-controller
    networks:
      - jenkins-network

  ansible-agent:
    build:
      context: .
      dockerfile: Dockerfile.ansible_agent
    container_name: ansible-agent
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_ANSIBLE_AGENT_SSH_PUBKEY}
    volumes:
      - ansible_agent_volume:/home/jenkins/agent
      - ./ansible:/home/jenkins/ansible
      - ./secrets/ansible_to_test_server:/home/jenkins/.ssh/ansible_key:ro
    depends_on:
      - jenkins-controller
      - test-server
    networks:
      - jenkins-network

  test-server:
    build:
      context: .
      dockerfile: Dockerfile.test_server
    container_name: test-server
    volumes:
      - ./secrets/ansible_to_test_server.pub:/home/ansible/.ssh/authorized_keys:ro
    networks:
      - jenkins-network

volumes:
  jenkins_home:
  jenkins_agent_volume:
  ansible_agent_volume:

networks:
  jenkins-network:
    driver: bridge